[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "netlify/functions"

[context.production.environment]
  REACT_APP_API_KEY = "Kiyaan07"
  REACT_APP_AUTH_URL = "https://www.dha.gov.za"
  REACT_APP_PORTAL_URL = "https://www.dha.gov.za"
  REACT_APP_BACK_OFFICE_URL = "https://www.dhadmin.gov.za"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
